# Generated by Django 5.2.4 on 2025-07-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cost_price", models.FloatField()),
                ("selling_price", models.FloatField()),
                (
                    "condition",
                    models.CharField(
                        choices=[("New", "New"), ("Good", "Good"), ("Scrap", "Scrap")],
                        max_length=10,
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                ("sold_b2b", models.BooleanField(default=False)),
                ("sold_direct", models.BooleanField(default=False)),
            ],
        ),
    ]
